---
title: "DS202-FinalProject"
author: "Corbin Graham, Coleman Dimmer"
date: "2023-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dataset

Milan

### Importing Data

```{r}
library(tidyverse)
data <- read_csv("milan.csv")
head(data)
```
### Data Timeframe

```{r}
min(data$DATE)
max(data$DATE)
#summary(data)
str(data)
data
```

### Description

The dataset we chose is monthly climate data recorded in Milan, Italy, between January 1763 and November 2008. We can use this data to analyze climate patterns. etc.

## Cleaning the Data

```{r}

#Grabs data and names columns to more reasonable col names. NOTE: DX and DY values are in degrees F, so changed to more accurate degrees C titles to match all other vars. 
milanClimate <- data %>%
  select(
    DATE,
    MEAN = TAVG,
    MEAN_MAX = TMAX,
    MEAN_MIN = TMIN,
    HEAT_DEG_DAYS = HTDD,
    COOL_DEG_DAYS = CLDD,
    HIGHEST_TEMP = EMXT,
    HIGHEST_DAY = EMXT_ATTRIBUTES,
    COOLEST_TEMP = EMNT,
    COOLEST_DAY = EMNT_ATTRIBUTES,
    GTE_32 = DX90,
    GTE_21 = DX70,
    GTE_00 = DX32,
    LTE_00 = DT32,
    LTE_N18 = DT00
  )

milanClimate$HIGHEST_DAY <- as.numeric(substr(gsub('\\D','',milanClimate$HIGHEST_DAY), nchar(gsub('\\D','',milanClimate$HIGHEST_DAY))-1, nchar(gsub('\\D','',milanClimate$HIGHEST_DAY))))

milanClimate$COOLEST_DAY <- as.numeric(substr(gsub('\\D','',milanClimate$COOLEST_DAY), nchar(gsub('\\D','',milanClimate$COOLEST_DAY))-1, nchar(gsub('\\D','',milanClimate$COOLEST_DAY))))
```

## Marginal Summaries
